New log file opened at Sat Dec 10 00:54:14 CET 2016 by 6544@DESKTOP-80HM3MF
Taking next connection to: 63727
New client attempting to connect on port: 63728-63727
  Address = /192.168.1.4:63727
This client on port 63728 has uuid f14fc038-392f-4b32-98e1-1f63d6145c06 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-f14fc038-392f-4b32-98e1-1f63d6145c06
Taking next connection to: 63727
New client attempting to connect on port: 63732-63727
  Address = /192.168.1.4:63727
Handshake exception on socket: 63732
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 63727
New client attempting to connect on port: 63733-63727
  Address = /192.168.1.4:63727
This client on port 63733 has uuid 648b007b-46da-48bc-b142-1304dbf681cb configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-f14fc038-392f-4b32-98e1-1f63d6145c06, play-fork-run-648b007b-46da-48bc-b142-1304dbf681cb
Taking next connection to: 63727
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 63727
